#!/usr/bin/env bash

PIPELINE_SCRIPT_LOCATION=pipeline
source ${PIPELINE_SCRIPT_LOCATION}/docker/docker-functions
source ../pipeline/docker/docker-functions 2>/dev/null # For IntelliJ/BashSupport's method binding

__buildImages() {
    [[ $# -eq 1 ]] || { >&2 echo "Usage: $0 $FUNCNAME VERSION"; return 1; }
    local version=$1
    buildImage jenkins-plugins ${version} || return 1
    buildImage jenkins ${version} "--build-arg PLUGINS_VERSION=${version}" || return 1
    buildImage nexus ${version} || return 1
}

verify() {
    __buildImages DEV-SNAPSHOT
}

deliver() {
    [[ $# -eq 3 ]] || { >&2 echo "Usage: $0 $FUNCNAME VERSION USERNAME PASSWORD"; return 1; }
    local version=$1
    local username=$2
    local password=$3
    __buildImages ${version} || return 1
    pushImage jenkins-plugins ${version} "${username}" "${password}" || return 1
    pushImage jenkins ${version} "${username}" "${password}" || return 1
    pushImage nexus ${version} "${username}" "${password}" || return 1
}

case $1 in
    verify)
        shift
        verify
        ;;
    deliver)
        shift
        deliver ${@}
        ;;
    *)
        >&2 echo "Usage $0 deliver|verify ..."
        ;;
esac
