#!/usr/bin/env bash

run() {
    [[ $# -eq 2 ]] || { >&2 echo "Usage: $0 STACK_NAME VERSION"; return 1; }
    local stackName=$1
    local version=$2
    workDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    stackFile="${workDir}/stack.yml"
    VERSION=${version} uid=1797 gid=503 docker stack deploy --prune --resolve-image never -c ${stackFile} ${stackName}
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && run ${@}
