#!/usr/bin/env bash

checkLabel() {
    local label=$1
    local nodeId=$2
    value=$(docker node inspect ${nodeId} | jq ".[].Spec.Labels.\"${label}\"") || { echo "Failed to inspect node"; return 1; }
    [[ 'null' == ${value} ]] && {
        read -p "Node label '${label}' not set. Set it? [Y/n] " answer
        [[ -z ${answer} ]] && answer='y'
        [[ ${answer} =~ [yY] ]] && { docker node update ${nodeId} --label-add ${label}=true; } || { echo "Failed to create label"; return 1; }
    } || return 0
}

docker node ls 2>&1 >/dev/null || {
    read -p "Enable swarm mode in Docker? [Y/n] " answer
    [[ -z ${answer} ]] && answer='y'
    [[ ${answer} =~ [yY] ]] && { docker swarm init; } || { exit 1; }
}

nodeId=$(docker node inspect self | jq -r ".[].ID") || exit 1
checkLabel jenkins-slave ${nodeId} || exit 1
checkLabel jenkins-master ${nodeId} || exit 1
checkLabel nexus ${nodeId} || exit 1

if [[ pipeline == $(docker stack ls --format {{.Name}}) ]]; then
    docker stack rm pipeline || exit 1
fi

[[ -z $(docker secret ls -q) ]] && {
    read -p "No secrets found in Docker's vault. Create dummy secrets? [Y/n] " answer
    [[ -z ${answer} ]] && answer='y'
    [[ ${answer} =~ [yY] ]] && { utils/create-dummy-secrets; } || { exit 1; }
}

[[ ! -z $(docker config ls -qf name=pipeline-jobs) ]] && {
    docker config rm pipeline-jobs || exit 1
}
utils/create-jobs-config || exit 1

[[ -z $(docker config ls -qf name=pipeline-config) ]] && {
    read -p "Configuration 'pipeline-config' not found in Docker. Create dummy config? [Y/n] " answer
    [[ -z ${answer} ]] && answer='y'
    [[ ${answer} =~ [yY] ]] && { utils/create-config; } || { exit 1; }
}

while [[ ! -z $(docker network ls -qf name=pipeline_pipeline) ]]; do
    echo "Waiting for stack to be removed..."
    sleep 1
done

[[ ! -z $(docker volume ls -qf name=jenkins-builds) ]] && {
    echo "Removing volume jenkins-builds"
    docker volume rm jenkins-builds || exit 1
}

mvn package -DskipTests || exit 1
docker/build-images local || exit 1
stackFile="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/stack.yml"
localStackFile="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/stack-local.yml"
REGISTRY=local VERSION=latest docker stack deploy --prune --resolve-image never -c ${stackFile} pipeline
REGISTRY=local VERSION=latest docker stack deploy --resolve-image never -c ${localStackFile} pipeline
