#!/usr/bin/env bash

echo "
jira:
  url: http://jira
  statuses:
    open: 1
    inProgress: 3
    codeApproved: 10005
    codeReview: 10012
    manualVerification: 10009
    manualVerificationOk: 10010
  transitions:
    start: 371
    readyForCodeReview: 391
    resumeWork: 301

crucible:
  url: http://crucible
  projectKey: CR

ssh:
  knownHosts:
    - github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
" | docker config create pipeline-config -