#!/usr/bin/env bash

createSecrets() {
    local secretNames=( \
        artifactory-cleaner \
        artifactory_username \
        artifactory_password \
        crucible_username \
        crucible_password \
        dockerHub_username \
        dockerHub_password \
        dockerHubAzureRelease_username \
        dockerHubAzureRelease_password \
        artifactory_username \
        artifactory_password \
        jira_username \
        jira_password \
        aws_username \
        aws_password \
        gitlab-api \
        dependency-track-api\
        polling_agent_jenkins_username\
        polling_agent_jenkins_password password\
    )
    for secretName in ${secretNames[*]}; do
        createSecret ${secretName} "${RANDOM}" || return 1
    done

    ssh-keygen -t rsa -f /tmp/gitkey -N "" || return 1
    createSecret ssh.git.difi.local "$(cat /tmp/gitkey)" || return 1
    createSecret ssh.eid-build.github.com "$(cat /tmp/gitkey)" || return 1
    rm /tmp/gitkey
    privateKey="$(cat ~/.ssh/id_rsa)" || return 1
    createSecret ssh.eid-build.github.com "${privateKey}" || return 1 # Used for accessing Jenkins shared library on GitHub
    createSecret nexus_username admin || return 1
    createSecret nexus_password admin123 || return 1
    createSecret nexus_jenkins_username admin || return 1
    createSecret nexus_jenkins_password admin123 || return 1
}

createSecret() {
    local name=$1
    local secret=$2
    docker secret rm ${name}
    echo "${secret}" | docker secret create ${name} - || return 1
}

createSecrets
