#!/usr/bin/env bash

createSecrets() {
    local secretNames=( \
        docker_registry_StagingLocal_username \
        docker_registry_StagingLocal_password \
        docker_registry_StagingPublic_username \
        docker_registry_StagingPublic_password \
        docker_registry_ProductionLocal_username \
        docker_registry_ProductionLocal_password \
        docker_registry_ProductionPublic_username \
        docker_registry_ProductionPublic_password \
        artifactory-cleaner \
        artifactory_username \
        artifactory_password \
        crucible_username \
        crucible_password \
        dockerHub_username \
        dockerHub_password \
        artifactory_username \
        artifactory_password \
        jira_username \
        jira_password \
        aws_username \
        aws_password \
        docker-ca.eid-jenkins03.dmz.local \
        docker-cert.eid-jenkins03.dmz.local \
        docker-key.eid-jenkins03.dmz.local \
        docker-ca.eid-jenkins02.dmz.local \
        docker-cert.eid-jenkins02.dmz.local \
        docker-key.eid-jenkins02.dmz.local \
    )
    for secretName in ${secretNames[*]}; do
        createSecret ${secretName} "${RANDOM}"
    done

    ssh-keygen -t rsa -f /tmp/gitkey -N ""
    createSecret ssh.github.com "$(cat /tmp/gitkey)"
    rm /tmp/gitkey
    createSecret ssh.git.difi.local "$(cat ~/.ssh/id_rsa)" # Used for accessing Jenkins shared library on GitHub
    createSecret nexus_username admin
    createSecret nexus_password admin123
}

createSecret() {
    local name=$1
    local secret=$2
    docker secret rm ${name}
    echo "${secret}" | docker secret create ${name} -
}

createSecrets
