#!/usr/bin/env bash

echo "
jenkins:
  url: http://jenkins
  adminAddress: Jenkins &lt;utvtest@difi.no&gt;

jira:
  url: http://jira.difi.local
  issues:
    bug: 11
  fields:
    sourceCodeRepository: 12380
  statuses:
    open: 1
    inProgress: 3
    readyForVerification: 10717
    codeApproved: 10005
    codeReview: 10012
    manualVerification: 10009
    manualVerificationOk: 10010
    manualVerificationFailed: 10917
  transitions:
    start: 371
    readyForCodeReview: 391
    startVerification: 291
    cancelVerification: 401
    resumeWork: 301
    resumeWorkFromApprovedCode: 331
    startManualVerification: 311
    approveManualVerification: 51
    retryManualVerificationFromSuccess: 441
    retryManualVerificationFromFailure: 421
    closeWithoutStaging: 361
    close: 341

crucible:
  url: http://crucible
  projectKey: CR

docker:
  registries:
    StagingLocal:
      address: docker-registry-staging-local
      apiUrl: https://docker-registry-staging-local-api
    ProductionLocal:
      address: docker-registry-local
      apiUrl: https://docker-registry-production-local-api
    StagingPublic:
      address: docker-registry-staging-public
    ProductionPublic:
      address: docker-registry-public

ssh:
  knownHosts:
    - github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
" | docker config create pipeline-config -