#!/usr/bin/env bash

echo "
jenkins:
  url: http://jenkins
  adminAddress: Jenkins &lt;jenkins@example.com&gt;

jira:
  url: http://jira
  issues:
    bug: 11
  fields:
    sourceCodeRepository: 12380
    buildVersion: 12480
  statuses:
    open: 1
    inProgress: 3
    readyForVerification: 10717
    codeApproved: 10005
    codeReview: 10012
    manualVerification: 10009
    manualVerificationOk: 10010
    manualVerificationFailed: 10917
    closed: 6
  transitions:
    start: 371
    readyForCodeReview: 391
    startVerification: 291
    cancelVerification: 401
    approveCode: 411
    resumeWork: 301
    resumeWorkFromApprovedCode: 331
    startManualVerification: 311
    approveManualVerification: 51
    failManualVerification: 61
    failStagingDeploy: 451
    retryManualVerificationFromSuccess: 441
    retryManualVerificationFromFailure: 421
    closeWithoutStaging: 361
    close: 341

crucible:
  url: http://crucible
  projectKey: CR

environments:
  staging:
    mavenRepository: StagingLocal

maven:
  repositories:
    StagingLocal:
      address: http://nexus:8081/repository/maven-releases
      credentialsId: nexus

docker:
  registries:
    StagingLocal:
      address: docker-registry-staging-local
      apiUrl: https://docker-registry-staging-local-api
    ProductionLocal:
      address: docker-registry-local
      apiUrl: https://docker-registry-production-local-api
    StagingPublic:
      address: docker-registry-staging-public
    ProductionPublic:
      address: docker-registry-public

ssh:
  knownHosts:
    - git ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAHJg2dXZC+cRBqryLjqr0rwkQnmWJzoMxePow/tbyJo5CIVVMFuagPT98UWM5tdnYkpKHoFjGrhotQF8MZApgo=

git:
  userName: Jenkins
  userEmail: jenkins@example.com
" | docker config create pipeline-config -