#!/usr/bin/env bash

createSecrets() {
    local secretNames=(ssh.git.difi.local ssh.github.com artifactory-cleaner artifactory_username artifactory_password crucible_username crucible_password nexus_username nexus_password jira_username jira_password docker-ca.eid-jenkins03.dmz.local docker-cert.eid-jenkins03.dmz.local docker-key.eid-jenkins03.dmz.local docker-ca.eid-jenkins02.dmz.local docker-cert.eid-jenkins02.dmz.local docker-key.eid-jenkins02.dmz.local)
    local secretName
    for secretName in ${secretNames[*]}; do
        echo $RANDOM | docker secret create ${secretName} -
    done
}

createSecrets
