#!/usr/bin/env bash

[[ $# -eq 1 ]] || { >&2 echo "Usage: $0 JENKINS_BASE_URL"; exit 1; }
jenkinsBaseUrl=$1

curl -sSf "${jenkinsBaseUrl}/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" | \
    perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1:\2\n/g' | sort
